
{% set data = load_setup_py_data() %}

package:
  name: snakeobjects
  
  #version: {{ data['version'] }}
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  noarch: python

  entry_points:
    - sobjects = snakeobjects.cli:cli
  #entry_points:
  #  {% for entry in data['entry_points']['console_scripts'] %}
  #    - {{ entry.split('=')[0].strip() }} = {{ entry.split('=')[1].strip() }}
  #  {% endfor %}
  

requirements:
  host:
    - python
    - pip
  run:
    - python
    - snakemake-minimal
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    {# raw is for ignoring templating with cookiecutter, leaving it for use with conda-build #}

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - snakemake-minimal
  commands:
    - pytest tests

about:
  home: https://github.com/iossifovlab/snakeobjects
  summary: Our pipeline infrastructure.
  license: {{ data.get('license') }}
  license_file: LICENSE
