{% set data = load_setup_py_data() %}

package:
  name: snakeobjects
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/iossifovlab/snakeobjects.git
  git_rev: HEAD
  git_deps: 1

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  noarch: python
  number: 0
  entry_points:
    - sobjects = snakeobjects.cli:cli
  
requirements:
  host:
    - python
    - pip
  run:
    - python
    - snakemake-minimal

test:
  imports:
    - snakeobjects
  commands:
    - sobjects --help
    - sobjects version

about:
  home: https://github.com/iossifovlab/snakeobjects
  summary: Snakeobjects, an object-oriented workflow management system based on snakemake
  license: MIT
  license_file: LICENSE

extra:
  maintainers:
   - yamrom
